version: '3.8'

services:
  app:
    build: .
    image: crowdfund-app
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
        max_attempts: 3
    environment:
      - NODE_ENV=production
      - REDIS_HOST=redis
      - CONSUL_HOST=consul
    depends_on:
      - redis
      - consul

  redis:
    image: redis:alpine
    volumes:
      - redis_data:/data
    deploy:
      placement:
        constraints: [node.role == worker]

  consul:
    image: consul:latest
    command: agent -server -bootstrap-expect=1 -ui -client=0.0.0.0
    volumes:
      - consul_data:/consul/data
    ports:
      - "8500:8500"
    deploy:
      placement:
        constraints: [node.role == manager]

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    depends_on:
      - prometheus
    ports:
      - "3000:3000"

volumes:
  redis_data:
  consul_data: 